# Generated by Codex on 2026-03-31

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def force_spanish_defaults(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    UserProfile = apps.get_model("zerver", "UserProfile")
    UserProfile.objects.exclude(default_language="es").update(default_language="es")

    RealmUserDefault = apps.get_model("zerver", "RealmUserDefault")
    RealmUserDefault.objects.exclude(default_language="es").update(default_language="es")

    PreregistrationRealm = apps.get_model("zerver", "PreregistrationRealm")
    PreregistrationRealm.objects.exclude(default_language="es").update(default_language="es")

    Realm = apps.get_model("zerver", "Realm")
    Realm.objects.exclude(default_language="es").update(default_language="es")


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0753_remove_google_blob_emojiset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="default_language",
            field=models.CharField(default="es", max_length=50),
        ),
        migrations.AlterField(
            model_name="realmuserdefault",
            name="default_language",
            field=models.CharField(default="es", max_length=50),
        ),
        migrations.AlterField(
            model_name="realm",
            name="default_language",
            field=models.CharField(default="es", max_length=50),
        ),
        migrations.AlterField(
            model_name="preregistrationrealm",
            name="default_language",
            field=models.CharField(default="es", max_length=50),
        ),
        migrations.RunPython(
            force_spanish_defaults,
            elidable=True,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
